/**
  ******************************************************************************
  * file           : example.c
  * brief          : example program body
  ******************************************************************************
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* Includes ------------------------------------------------------------------*/
#include "example.h"
#include "st25dvxxkc.h"
#include "stdio.h"
#include "mx_st25dvxxkc.h"
#include "basic_stdio_itf_io.h"
/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/


/* Private variables */
char uartmsg[80];
uint8_t writedata = 0xAA;
uint8_t readdata = 0x0;
uint8_t cnt = 0;
uint32_t st25dvxxkcbmsize = 0;
uint32_t memindex = 0;
st25dvxxkc_passwd_t passwd;
st25dvxxkc_i2csso_status_e i2csso;
st25dvxxkc_mem_size_t st25dvxxkcmemsize;
uint32_t ret;

uint32_t Button_TimeCount;
st25dvxxkc_object_t obj;

/**
  * ########## Step 1 ##########
  * The init of ST25DV is triggered by the applicative code
  * The initialization code is generated by STM32CubeMX2 under the targets folder.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see stm32_mcu_def.h.
  * output: EXEC_STATUS_INIT_OK if OK, EXEC_STATUS_ERROR in case of error
  */

app_status_t app_init(void)
{

  /* Init of the Leds on X-NUCLEO-NFC07A1 board */
  PRINTF("GREEN LED INIT\n");
  PRINTF("BLUE LED INIT\n");
  PRINTF("YELLOW LED INIT\n");

  PRINTF("GREEN LED ON\n");
  HAL_Delay(300);
  PRINTF("BLUE LED ON\n");
  HAL_Delay(300);
  PRINTF("YELLOW LED ON\n");
  HAL_Delay(300);

  /* Init ST25DVXXKC driver */

  while (st25dvxxkc_drv_init(&obj, ST25DVXXKC_0) != NFCTAG_OK);

  /* Init done */
  PRINTF("GREEN LED OFF\n");
  HAL_Delay(300);
  PRINTF("BLUE LED OFF\n");
  HAL_Delay(300);
  PRINTF("YELLOW LED OFF\n");
  HAL_Delay(300);

  /* Init UART for display message on console */
  PRINTF("----------------------------------------");
  PRINTF("\n\r*****Welcome to x-cube-nfc7 example*****");
  PRINTF("\n\r----------------------------------------");

  /* Reset Mailbox enable to allow write to EEPROM */
  st25dvxxkc_drv_resetmben_dyn(&obj);

  /* You need to present password to change static configuration */
  st25dvxxkc_drv_readi2csecuritysession_dyn(&obj, &i2csso);

  if (i2csso == ST25DVXXKC_SESSION_CLOSED)
  {
    /* if I2C session is closed, present password to open session */
    passwd.msbpasswd = 0;
    passwd.lsbpasswd = 0;
    st25dvxxkc_drv_presenti2cpassword(&obj, passwd);
  }

  /* Get ST25DVXXKC EEPROM size */
  st25dvxxkc_drv_readmemsize(&obj, &st25dvxxkcmemsize);

  /* st25dvxxkcmemsize is composed of Mem_Size (number of blocks) and BlockSize (size of each blocks in bytes) */
  st25dvxxkcbmsize = (st25dvxxkcmemsize.mem_size + 1) * (st25dvxxkcmemsize.blocksize + 1);

  PRINTF("\n\r\n\rThis example will create 4 zones in the ST25DVXXKC,");
  PRINTF("\n\rset different protection for each zone and test read/write on it");
  /* Set mapping configuration on ST25DVXXKC, create 4 identical zone
  Mapping example for a STDV64:
                 _______________
           @0000|               |
                |               |
                |     Zone 1    |
                |               |
           @2048|---------------|
                |               |
                |     Zone 2    |
                |               |
           @4096|---------------|
                |               |
                |     Zone 3    |
                |               |
           @6144|---------------|
                |               |
                |     Zone 4    |
                |               |
           @8192|_______________|
  */

  st25dvxxkc_drv_createuserzone(&obj, (st25dvxxkcbmsize / 4), (st25dvxxkcbmsize / 4), (st25dvxxkcbmsize / 4),
                                (st25dvxxkcbmsize / 4));

  PRINTF("\n\rZone 1 is not protected");
  /*Unprotect zone 1*/
  st25dvxxkc_drv_writei2cprotectzonex(&obj, ST25DVXXKC_PROT_ZONE1,  ST25DVXXKC_NO_PROT);

  PRINTF("\n\rZone 2 is write protected");
  /*Protect zone 2 for i2c write without password */
  st25dvxxkc_drv_writei2cprotectzonex(&obj, ST25DVXXKC_PROT_ZONE2,  ST25DVXXKC_WRITE_PROT);

  PRINTF("\n\rZone 3 is read protected");
  /* Protect zone 3 for i2c read without password */
  st25dvxxkc_drv_writei2cprotectzonex(&obj, ST25DVXXKC_PROT_ZONE3,  ST25DVXXKC_READ_PROT);

  PRINTF("\n\rZone 4 is read/write protected");
  /* Protect zone 4 for i2c read and write without password */
  st25dvxxkc_drv_writei2cprotectzonex(&obj, ST25DVXXKC_PROT_ZONE4,  ST25DVXXKC_READWRITE_PROT);

  PRINTF("\n\r\n\rPress a key to continue...");
  /*   UARTConsoleScan( readdata );*/ /* BMP */

  PRINTF("\n\r\n\rSession is closed to see protections in operation");
  /* Session is open, present wrong password to closed it */
#define INVALID_PASSWD_VALUE ((uint8_t)123)
  passwd.msbpasswd = INVALID_PASSWD_VALUE;
  passwd.lsbpasswd = INVALID_PASSWD_VALUE;
  st25dvxxkc_drv_presenti2cpassword(&obj, passwd);

  for (cnt = 1; cnt < 5; cnt++)
  {
    /* Compute memory index for each zone */
    memindex = (((st25dvxxkcbmsize / 4) + 1) * (cnt - 1));

    sprintf(uartmsg, "\n\r\n\rStart writing Zone %d", cnt);
    PRINTF("%s", uartmsg);
    ret = st25dvxxkc_drv_writedata(&obj, &writedata, memindex, 1);
    if (ret != NFCTAG_OK)
    {
      sprintf(uartmsg, "\n\rWrite Zone %d protected, need i2c password", cnt);
      PRINTF("%s", uartmsg);
    }
    else
    {
      sprintf(uartmsg, "\n\rWrite Zone %d done", cnt);
      PRINTF("%s", uartmsg);
    }

    sprintf(uartmsg, "\n\r\n\rStart reading Zone %d", cnt);
    PRINTF("%s", uartmsg);
    ret = st25dvxxkc_drv_readdata(&obj, &readdata, memindex, 1);
    if (readdata == 0xFF)
    {
      sprintf(uartmsg, "\n\rRead Zone %d protected, need i2c password", cnt);
      PRINTF("%s", uartmsg);
    }
    else
    {
      sprintf(uartmsg, "\n\rRead Zone %d done", cnt);
      PRINTF("%s", uartmsg);
    }
  }

  PRINTF("\n\r\n\rPress a key to continue...");

  PRINTF("\n\r\n\rSession is open to see granted access");
  /* Session is closed, present password to open it */
  passwd.msbpasswd = 0;
  passwd.lsbpasswd = 0;
  st25dvxxkc_drv_presenti2cpassword(&obj, passwd);

  for (cnt = 1; cnt < 5; cnt++)
  {
    /* Compute memory index for each zone */
    memindex = (((st25dvxxkcbmsize / 4) + 1) * (cnt - 1));

    sprintf(uartmsg, "\n\r\n\rStart writing Zone %d", cnt);
    PRINTF("%s", uartmsg);
    ret = st25dvxxkc_drv_writedata(&obj, &writedata, memindex, 1);
    if (ret != NFCTAG_OK)
    {
      sprintf(uartmsg, "\n\rWrite Zone %d protected, need i2c password", cnt);
      PRINTF("%s", uartmsg);
    }
    else
    {
      sprintf(uartmsg, "\n\rWrite Zone %d done", cnt);
      PRINTF("%s", uartmsg);
    }

    sprintf(uartmsg, "\n\r\n\rStart reading Zone %d", cnt);
    PRINTF("%s", uartmsg);
    ret = st25dvxxkc_drv_readdata(&obj, &readdata, memindex, 1);
    if (readdata == 0xFF)
    {
      sprintf(uartmsg, "\n\rRead Zone %d protected, need i2c password", cnt);
      PRINTF("%s", uartmsg);
    }
    else
    {
      sprintf(uartmsg, "\n\rRead Zone %d done", cnt);
      PRINTF("%s", uartmsg);
    }
  }

  PRINTF("\n\r\n\r----------------------------------------");
  PRINTF("\n\r*****        end of example        *****");
  PRINTF("\n\r----------------------------------------\n\r");

  return EXEC_STATUS_INIT_OK;
}

/**
  * ########## Step 2 ##########
  * Run the NFC Application Process.
  * The values are displayed on the terminal.
  * output: EXEC_STATUS_OK if OK, EXEC_STATUS_ERROR in case of error
  */

app_status_t app_process(void)
{
  app_status_t return_status = EXEC_STATUS_OK;

  return return_status;
}

/**
  * ########## Step 3 ##########
  * Deinitializes ST25DV before leaving the scenario.
  * The de-initialization code is generated by STM32CubeMX2 under the targets folder.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see stm32_mcu_def.h.
  * output: EXEC_STATUS_OK if OK, EXEC_STATUS_ERROR in case of error
  */
app_status_t app_deinit(void)
{
  return EXEC_STATUS_OK;
}



